name: build-release-latest
on:
  push:
    tags-ignore: 'v*'
    branches:
      - '**'
      - '!*.*.*'

env:
  python_win_version: 3.10.8
  repo_dir: nagstamon-jekyll/docs/repo
  cr_image: ghcr.io/henriwahl/build-nagstamon

jobs:
  windows-64:
    # better depend on stable build image
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python_win_version }}
          architecture: x64
      - run: python -m pip install --no-warn-script-location -r build/requirements/windows.txt
      # pretty hacky but no other idea to avoid gssapi being installed which breaks requests-kerberos
      - run: python -m pip uninstall -y gssapi requests-gssapi
      - run: cd ${{ github.workspace }}/build; python build.py
        env:
          PYTHONPATH: ${{ github.workspace }}
      - uses: actions/upload-artifact@v3
        with:
          path: |
            build/dist/*.zip
            build/dist/*.exe
          retention-days: 1
          if-no-files-found: error

  github-release:
    runs-on: ubuntu-latest
    needs: [windows-64]
    steps:
      - uses: actions/download-artifact@v3
      - run: cd artifact && md5sum *agstamon* > md5sums.txt
      - run: cd artifact && sha256sum *agstamon* > sha256sums.txt
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            artifact/*
